import {
  Building2,
  Code,
  DollarSign,
  Megaphone,
  Shield,
  Heart,
  Briefcase,
  Palette,
  Users,
  Settings,
  Bot,
  Brain,
  Lightbulb,
  Target,
  Zap,
  Globe,
  Database,
  Monitor,
  Smartphone,
  Camera,
  Music,
  Video,
  FileText,
  Calculator,
  TrendingUp,
  BarChart3,
  PieChart,
  LineChart
} from 'lucide-react'

import type { IconOption } from '../types'

export const ICON_MAP = {
  Building2,
  Code,
  DollarSign,
  Megaphone,
  Shield,
  Heart,
  Briefcase,
  Palette,
  Users,
  Settings,
  Bot,
  Brain,
  Lightbulb,
  Target,
  Zap,
  Globe,
  Database,
  Monitor,
  Smartphone,
  Camera,
  Music,
  Video,
  FileText,
  Calculator,
  TrendingUp,
  BarChart3,
  PieChart,
  LineChart
}

export const ICON_OPTIONS: IconOption[] = [
  { name: 'Building2', component: Building2, category: 'business' },
  { name: 'Briefcase', component: Briefcase, category: 'business' },
  { name: 'Users', component: Users, category: 'business' },
  { name: 'TrendingUp', component: TrendingUp, category: 'business' },
  { name: 'BarChart3', component: BarChart3, category: 'business' },
  { name: 'PieChart', component: PieChart, category: 'business' },
  { name: 'LineChart', component: LineChart, category: 'business' },
  { name: 'DollarSign', component: DollarSign, category: 'finance' },
  { name: 'Calculator', component: Calculator, category: 'finance' },
  { name: 'Code', component: Code, category: 'technical' },
  { name: 'Database', component: Database, category: 'technical' },
  { name: 'Monitor', component: Monitor, category: 'technical' },
  { name: 'Smartphone', component: Smartphone, category: 'technical' },
  { name: 'Globe', component: Globe, category: 'technical' },
  { name: 'Bot', component: Bot, category: 'ai' },
  { name: 'Brain', component: Brain, category: 'ai' },
  { name: 'Zap', component: Zap, category: 'ai' },
  { name: 'Target', component: Target, category: 'ai' },
  { name: 'Palette', component: Palette, category: 'creative' },
  { name: 'Camera', component: Camera, category: 'creative' },
  { name: 'Music', component: Music, category: 'creative' },
  { name: 'Video', component: Video, category: 'creative' },
  { name: 'Megaphone', component: Megaphone, category: 'marketing' },
  { name: 'Heart', component: Heart, category: 'personal' },
  { name: 'Shield', component: Shield, category: 'security' },
  { name: 'Settings', component: Settings, category: 'system' },
  { name: 'FileText', component: FileText, category: 'system' },
  { name: 'Lightbulb', component: Lightbulb, category: 'general' }
]

export const DEFAULT_ICON = 'Bot'

export const CATEGORY_ICONS = {
  business: 'Building2',
  technical: 'Code',
  creative: 'Palette',
  personal: 'Heart',
  finance: 'DollarSign',
  marketing: 'Megaphone',
  ai: 'Bot',
  security: 'Shield',
  system: 'Settings',
  general: 'Lightbulb'
}